version: '3'
services:
  alloy:
    image: grafana/alloy:v1.3.1
    volumes:
      - "./alloy/config.alloy:/etc/alloy/config.alloy"
    environment:
      GRAFANA_CLOUD_OTLP_ENDPOINT: ${GRAFANA_CLOUD_OTLP_ENDPOINT}
      GRAFANA_CLOUD_INSTANCE_ID: ${GRAFANA_CLOUD_INSTANCE_ID}
      GRAFANA_CLOUD_TOKEN: ${GRAFANA_CLOUD_TOKEN}
    command: [
      "run",
      "--server.http.listen-addr=0.0.0.0:12345",
      "--stability.level=public-preview",
      "/etc/alloy/config.alloy",
    ]
    extra_hosts:
      - "host.docker.internal:host-gateway" 